import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(".");

test("ui inject script includes native sidebar delete hook and observer", async () => {
  const script = await fs.readFile(path.join(repoRoot, "inject-ui", "history-guard-ui.js"), "utf8");
  assert.match(script, /findSidebarRows/);
  assert.match(script, /attachSidebarDeleteButton/);
  assert.match(script, /ensureSidebarRepairEntry/);
  assert.match(script, /renderSidebarRepairEntry/);
  assert.match(script, /findSidebarLauncherInsertionPoint/);
  assert.match(script, /isLikelySidebar/);
  assert.match(script, /findNativeLauncherInsertionPoint/);
  assert.match(script, /ensureLauncherTrigger/);
  assert.match(script, /data-chg-trigger-mode="sidebar"|dataset\.chgTriggerMode = "sidebar"/);
  assert.match(script, /data-chg-trigger-mode="native"|dataset\.chgTriggerMode = "native"/);
  assert.match(script, /chg-launcher-icon/);
  assert.match(script, /codex-history-guard-sidebar-repair/);
  assert.match(script, /data-chg-sidebar-row/);
  assert.match(script, /hasNativeRightStatus/);
  assert.match(script, /isCurrentSessionRow\(row, threadId\)/);
  assert.match(script, /row\.dataset\.chgSidebarRow = "ignored"/);
  assert.match(script, /setAttribute\("aria-label", "移除会话"\)/);
  assert.match(script, /right:\s*32px/);
  assert.match(script, /focus-within/);
  assert.match(script, /MutationObserver\(scheduleSidebarScan\)/);
  assert.match(script, /DOMContentLoaded/);
  assert.match(script, /requestAnimationFrame\(waitForDomAndStart\)/);
  assert.match(script, /document\.body && document\.documentElement/);
  assert.match(script, /悬停|删除本地会话|撤销|修复历史/);
  assert.match(script, /evaluateDoctorIssues/);
  assert.match(script, /getRecoveryState/);
  assert.match(script, /resolvePrimaryRescue/);
  assert.match(script, /renderPrimaryCard/);
  assert.match(script, /primary-rescue/);
  assert.match(script, /chg-primary-card/);
  assert.match(script, /历史可能没显示完整/);
  assert.match(script, /本地记录还在。点一下，让它重新显示。/);
  assert.match(script, /修复历史显示/);
  assert.match(script, /重建历史索引/);
  assert.match(script, /打开高级修复/);
  assert.match(script, /需要重建历史索引/);
  assert.match(script, /先在面板里点“修复历史显示”。/);
  assert.match(script, /如果仍不完整，再点“重建历史索引”。/);
  assert.match(script, /已打开高级修复。/);
  assert.match(script, /不会改账号、模型或 API 地址。/);
  assert.match(script, /void refreshStatus\(\)/);
  assert.match(script, /data-field="injection"/);
  assert.match(script, /formatInjectionStatus/);
  assert.match(script, /安全回退/);
  assert.match(script, /已融入界面/);
  assert.match(script, /待确认/);
  assert.match(script, /历史/);
  assert.match(script, /高级/);
  assert.match(script, /暂停守护/);
  assert.match(script, /恢复守护/);
  assert.match(script, /打开日志目录/);
  assert.match(script, /打开安装目录/);
  assert.match(script, /打开快速开始/);
  assert.match(script, /检查更新/);
  assert.match(script, /update\/check/);
  assert.match(script, /checkUpdate/);
  assert.match(script, /update\/install/);
  assert.match(script, /installUpdate/);
  assert.match(script, /autoCheckUpdateNotice/);
  assert.match(script, /立即更新/);
  assert.match(script, /更多修复入口/);
  assert.match(script, /卸载说明/);
  assert.match(script, /showUninstallGuide/);
  assert.match(script, /open-start-menu-dir/);
  assert.match(script, /export-session-markdown/);
  assert.match(script, /导出 Markdown/);
  assert.match(script, /copyOrDownloadMarkdown/);
  assert.match(script, /handoff\/export/);
  assert.match(script, /生成交接包/);
  assert.match(script, /exportHandoff/);
  assert.match(script, /repair-plugin-entry/);
  assert.match(script, /插件/);
  assert.match(script, /repair-plugin-install/);
  assert.match(script, /恢复安装按钮/);
  assert.match(script, /findPluginInstallButtonCandidates/);
  assert.match(script, /buildConversationTimeline/);
  assert.match(script, /长对话跳转/);
  assert.match(script, /build-timeline/);
  assert.match(script, /jump-timeline/);
  assert.match(script, /本地记录还在，可以先修复显示。/);
  assert.match(script, /修复显示/);
  assert.match(script, /找回旧会话/);
  assert.match(script, /查找会话/);
  assert.match(script, /当前历史/);
  assert.match(script, /本地记录/);
  assert.match(script, /当前项目/);
  assert.match(script, /当前显示/);
  assert.match(script, /当前保护/);
  assert.match(script, /最近一次检查/);
  assert.match(script, /已显示 .*，本地 .*/);
  assert.match(script, /已经对齐|当前 .*，已记住 .*/);
  assert.match(script, /正在保护/);
  assert.match(script, /保护已暂停/);
  assert.match(script, /显示插件入口/);
  assert.match(script, /已生成 .* 个跳转点/);
  assert.match(script, /长对话跳转已生成。/);
  assert.match(script, /找回方式：/);
  assert.doesNotMatch(script, /历史与修复/);
  assert.match(script, /source_label/);
});

test("launcher supports reusing already-running Codex instance on default CDP port", async () => {
  const script = await fs.readFile(path.join(repoRoot, "launcher-python", "launcher.py"), "utf8");
  assert.match(script, /ensure_console_utf8/);
  assert.match(script, /缺少 Python 依赖/);
  assert.match(script, /py -m pip install -r/);
  assert.match(script, /find_codex_windowsapps_package/);
  assert.match(script, /find_codex_windowsapps_package_family/);
  assert.match(script, /is_cli_binary/);
  assert.match(script, /openai\\\\codex\\\\bin\\\\codex\.exe/);
  assert.match(script, /app\\\\resources\\\\codex\.exe/);
  assert.match(script, /shell:AppsFolder/);
  assert.match(script, /Windows app activation/);
  assert.match(script, /Get-ChildItem .*WindowsApps/);
  assert.match(script, /cdp_targets_if_running/);
  assert.match(script, /Reusing already-running Codex instance on default CDP port/);
  assert.match(script, /检测到 Codex 已经在运行，这次先继续使用当前窗口|当前已经有一个 Codex 窗口在运行，这次页面增强没能直接附着到它/);
  assert.match(script, /这次页面增强没有挂到当前窗口|页面增强没能挂上去/);
  assert.match(script, /LAUNCH_LOCK_FILENAME/);
  assert.match(script, /acquire_launch_lock/);
  assert.match(script, /release_launch_lock/);
  assert.match(script, /skipping duplicate launch/);
  assert.match(script, /continuing with isolated probe/);
  assert.match(script, /检测到 Codex 当前已经在运行，诊断将继续使用隔离用户目录和独立端口做探测/);
  assert.match(script, /这通常不是你启动方式不对，而是官方正式桌面包本身限制了注入链/);
  assert.match(script, /开始菜单里的 Repair History/);
  assert.match(script, /summarize_history_health/);
  assert.match(script, /检测到历史异常：/);
  assert.match(script, /Repair History/);
  assert.match(script, /Boolean\(window\.__CODEX_PRO_INSTALLED__ \|\| window\.__CODEX_HISTORY_GUARD_INSTALLED__\)/);
  assert.match(script, /已连接到 Codex 页面，但这次没有挂上“历史”入口/);
  assert.match(script, /--diagnose-cdp/);
  assert.match(script, /cdp-diagnosis\.json/);
  assert.match(script, /Skipping injection attempt because cached diagnosis says current build is unsupported/);
  assert.match(script, /当前先按兼容方式继续使用，历史保护仍生效/);
  assert.match(script, /start_codex_plain/);
  assert.match(script, /兼容模式/);
  assert.match(script, /Codex 已按原生方式启动；以后继续像平常一样打开 Codex 即可/);
  assert.doesNotMatch(script, /BUILD_FLAVOR/);
});
